
.set XexpConvertError, 0x8007af30
.set XexpLoadXexHeadersPatch, 0x8007bac8
.set BadNetworkNamePatch, 0x8007bbd8
.set ResourceNotFound1Patch, 0x8007bc40
.set ResourceNotFound2Patch, 0x8007bc90
.set XexpVerifyMinimumVersion, 0x8007a518
.set SfcxFixBBSizePatch, 0x800941d8
.set SataCdRomAuthenticationExInitializePatch, 0x80098ac8
.set E66xgd3, 0x800984ac
.set XeKeysVerifyRSASignature, 0x8010a1a0
.set XeKeysSecurityConvertError, 0x8010ac98
.set XeKeysDvdAuthExConvertError, 0x8010af78
.set _XeKeysRevokeIsValid, 0x8010b440
.set XeKeysRevokeIsRevoked, 0x8010b648
.set XeKeysRevokeIsDeviceRevoked, 0x8010b788
.set XeKeysRevokeConvertError, 0x8010b908
.set XeKeysConsoleSignatureVerificationPatch, 0x8010c480
.set XeKeysConsoleSignatureVerificationDestPatch, 0x8010c4a8
.set XeCryptBnQwBeSigVerify, 0x80110dd0
.set SataDiskAuthenticateDevice, 0x801591a0
.set XexLoadImage, 0x8007cd10
.set XexLoadExecutablePatch, 0x8007cd48
.set AddonNoNandMuPatch, 0x8008d458
.set AddonNoFcrtPhase1Patch, 0x800611a0
.set AddonNoHdmiWaitPatch, 0x80157820
.set AddonNoHdmiWaitDestPatch, 0x8015786c
.set SataChannelDetectDevice, 0x801594f8
# STATUS: named SataDiskInitialize at 0x801592e0
.set AddonNoTrinMuPatch, 0x800e31a0
.set NoWiredLan, 0x800d2a7c
# STATUS: named NicDriverEntry at 0x800d2a58
.set AddonNoCorMuPatch, 0x8008e780
