#ifndef _XEXHEADER_H
#define _XEXHEADER_H

#define XEX_HEADER_MAGIC		0x58455832 //'XEX2'

#define XEX_SECURITY_FLAG_MFG_MODE          0x00000006
#define XEX_SECURITY_FLAG_MFG_UTIL          0x00000002 // runs in verified mfg mode
#define XEX_SECURITY_FLAG_MFG_SUPPORT       0x00000004 // runs in all mfg modes
#define XEX_SECURITY_FLAG_MFG_AWARE         0x00000006 // runs in all modes
#define XEX_SECURITY_FLAG_XGD2_MEDIA        0x00000008
#define XEX_SECURITY_FLAG_HV_PRIVS_MASK     0x000FFF00
#define XEX_SECURITY_FLAG_HV_PRIVS_SHIFT        8
#define XEX_SECURITY_FLAG_SMALL_PAGES       0x10000000
#define XEX_SECURITY_FLAG_NO_REGION         0x20000000
#define XEX_SECURITY_FLAG_REVOCABLE         0x40000000
#define XEX_SECURITY_FLAG_REQUIRE_COOKIE    0x80000000

typedef struct _IMAGE_XEX_HEADER {
	DWORD Magic; // 0x0 sz:0x4
	DWORD ModuleFlags; // 0x4 sz:0x4
	DWORD SizeOfHeaders; // 0x8 sz:0x4
	DWORD SizeOfDiscardableHeaders; // 0xC sz:0x4
	DWORD SecurityInfo; // 0x10 sz:0x4
	DWORD HeaderDirectoryEntryCount; // 0x14 sz:0x4
} IMAGE_XEX_HEADER, *PIMAGE_XEX_HEADER; // size 24

typedef struct _HV_IMAGE_INFO {
	BYTE Signature[0x100]; // 0x0 sz:0x100
	DWORD InfoSize; // 0x100 sz:0x4
	DWORD ImageFlags; // 0x104 sz:0x4
	DWORD LoadAddress; // 0x108 sz:0x4
	BYTE ImageHash[0x14]; // 0x10C sz:0x14
	DWORD ImportTableCount; // 0x120 sz:0x4
	BYTE ImportDigest[0x14]; // 0x124 sz:0x14
	BYTE MediaID[0x10]; // 0x138 sz:0x10
	BYTE ImageKey[0x10]; // 0x148 sz:0x10
	DWORD ExportTableAddress; // 0x158 sz:0x4
	BYTE HeaderHash[0x14]; // 0x15C sz:0x14
	DWORD GameRegion; // 0x170 sz:0x4
} HV_IMAGE_INFO, *PHV_IMAGE_INFO; // size 372

typedef struct _XEX_SECURITY_INFO {
	DWORD Size; // 0x0 sz:0x4
	DWORD ImageSize; // 0x4 sz:0x4
	HV_IMAGE_INFO ImageInfo; // 0x8 sz:0x174
	DWORD AllowedMediaTypes; // 0x17C sz:0x4
	DWORD PageDescriptorCount; // 0x180 sz:0x4
} XEX_SECURITY_INFO, *PXEX_SECURITY_INFO; // size 388

typedef struct _XEX_EXECUTION_ID {
	DWORD MediaID; // 0x0 sz:0x4
	DWORD Version; // 0x4 sz:0x4
	DWORD BaseVersion; // 0x8 sz:0x4
	union {
		struct {
			WORD PublisherID; // 0xC sz:0x2
			WORD GameID; // 0xE sz:0x2
		} Sep;
		DWORD TitleID; // 0xC sz:0x4
	} Tid;
	BYTE Platform; // 0x10 sz:0x1
	BYTE ExecutableType; // 0x11 sz:0x1
	BYTE DiscNum; // 0x12 sz:0x1
	BYTE DiscsInSet; // 0x13 sz:0x1
	DWORD SaveGameID; // 0x14 sz:0x4
} XEX_EXECUTION_ID, *PXEX_EXECUTION_ID; // size 24
//C_ASSERT(sizeof(XEX_EXECUTION_ID) == 0x18);

typedef struct _XEX_SECTION_HEADER {
	char SectionName[0x8]; // 0x0 sz:0x8
	DWORD VirtualAddress; // 0x8 sz:0x4
	DWORD VirtualSize; // 0xC sz:0x4
} XEX_SECTION_HEADER, *PXEX_SECTION_HEADER; // size 16

typedef struct _XEX_SECTION_INFO {
	DWORD			   Size;
	XEX_SECTION_HEADER Section[1];
} XEX_SECTION_INFO, *PXEX_SECTION_INFO;

typedef struct _XEX_DATA_DESCRIPTOR {
	DWORD Size; // 0x0 sz:0x4
	BYTE DataDigest[0x14]; // 0x4 sz:0x14
} XEX_DATA_DESCRIPTOR, *PXEX_DATA_DESCRIPTOR; // size 24

#define XEX_DEFAULT_COMPRESSION_WINDOW      0x8000
typedef struct _XEX_COMPRESSED_DATA_DESCRIPTOR {
	DWORD WindowSize; // 0x0 sz:0x4
	XEX_DATA_DESCRIPTOR FirstDescriptor; // 0x4 sz:0x18
} XEX_COMPRESSED_DATA_DESCRIPTOR, *PXEX_COMPRESSED_DATA_DESCRIPTOR; // size 28

typedef struct _XEX_RAW_DATA_DESCRIPTOR {
	DWORD DataSize; // 0x0 sz:0x4
	DWORD ZeroSize; // 0x4 sz:0x4
} XEX_RAW_DATA_DESCRIPTOR, *PXEX_RAW_DATA_DESCRIPTOR; // size 8

#define XEX_DATA_FLAG_ENCRYPTED             0x0001
#define XEX_DATA_FORMAT_NONE                0x0000
#define XEX_DATA_FORMAT_RAW                 0x0001
#define XEX_DATA_FORMAT_COMPRESSED          0x0002
#define XEX_DATA_FORMAT_DELTA_COMPRESSED    0x0003

typedef struct _XEX_FILE_DATA_DESCRIPTOR {
	DWORD Size; // 0x0 sz:0x4
	WORD Flags; // 0x4 sz:0x2
	WORD Format; // 0x6 sz:0x2
	 union {
		 XEX_DATA_DESCRIPTOR data;
		 XEX_COMPRESSED_DATA_DESCRIPTOR compressed;
		 XEX_RAW_DATA_DESCRIPTOR raw[1];
	 } fmt;
} XEX_FILE_DATA_DESCRIPTOR, *PXEX_FILE_DATA_DESCRIPTOR; // size 8, without descriptors which follow but don't always expand struct size..


#define XEX_HEADER_STRUCT(key, struct)	(((key) << 8) | (sizeof (struct) >> 2))
#define XEX_HEADER_FIXED_SIZE(key, size)(((key) << 8) | ((size) >> 2))
#define XEX_HEADER_ULONG(key) 			(((key) << 8) | 1)
#define XEX_HEADER_FLAG(key) 			((key) << 8)
#define XEX_HEADER_SIZEDSTRUCT(key)		(((key) << 8) | 0xFF)
#define XEX_HEADER_STRING_FIELD(key)	XEX_HEADER_SIZEDSTRUCT(key)


// for RtlImageXexHeaderField, RtlImageXexHeaderString
#define XEX_HEADER_SECTION_TABLE			XEX_HEADER_SIZEDSTRUCT(0x0002)
#define XEX_FILE_DATA_DESCRIPTOR_HEADER		XEX_HEADER_SIZEDSTRUCT(0x0003)
#define XEX_PATCH_FILE_BASE_REFERENCE		XEX_HEADER_FIXED_SIZE(0x0004, 0x14)
#define XEX_HEADER_DELTA_PATCH_DESCRIPTOR	XEX_HEADER_SIZEDSTRUCT(5)
// #define XEX_HEADER_KEY_VAULT_PRIVS			XEX_HEADER_STRUCT(0x0040, XEX_KEY_VAULT_PRIVILEGES)
// #define XEX_HEADER_TIME_RANGE				XEX_HEADER_STRUCT(0x0041, XEX_SYSTEM_TIME_RANGE)
#define XEX_HEADER_CONSOLE_ID_TABLE			XEX_HEADER_SIZEDSTRUCT(0x0042) // lists disallowed console IDs
#define XEX_HEADER_BOUND_PATH				XEX_HEADER_STRING_FIELD(0x0080)
#define XEX_HEADER_DEVICE_ID				XEX_HEADER_FIXED_SIZE(0x0081, 0x14)
#define XEX_HEADER_ORIGINAL_BASE_ADDRESS	XEX_HEADER_ULONG(0x0100)
#define XEX_HEADER_ENTRY_POINT				XEX_HEADER_FLAG(0x0101)
#define XEX_HEADER_PE_BASE					XEX_HEADER_ULONG(0x0102)
#define XEX_HEADER_IMPORTS					XEX_HEADER_SIZEDSTRUCT(0x0103)
// #define XEX_HEADER_PE_EXPORTS				XEX_HEADER_STRUCT(0xE104, IMAGE_DATA_DIRECTORY)
// #define XEX_HEADER_VITAL_STATS				XEX_HEADER_STRUCT(0x0180, XEX_VITAL_STATS)
// #define XEX_HEADER_CALLCAP_IMPORTS			XEX_HEADER_STRUCT(0x0181, XEX_CALLCAP_IMPORTS)
#define XEX_HEADER_FASTCAP_ENABLED			XEX_HEADER_FLAG(0x0182)
#define XEX_HEADER_PE_MODULE_NAME			XEX_HEADER_STRING_FIELD(0x0183)
#define XEX_HEADER_BUILD_VERSIONS			XEX_HEADER_SIZEDSTRUCT(0x0200)
// #define XEX_HEADER_TLS_DATA					XEX_HEADER_STRUCT(0x201, XEX_TLS_DATA)
#define XEX_HEADER_STACK_SIZE				XEX_HEADER_FLAG(0x0202)
#define XEX_HEADER_FSCACHE_SIZE				XEX_HEADER_ULONG(0x203)
#define XEX_HEADER_XAPI_HEAP_SIZE			XEX_HEADER_ULONG(0x204)
// #define XEX_HEADER_PAGE_HEAP_SIZE_FLAGS		XEX_HEADER_STRUCT(0x0280, XEX_PAGE_HEAP_OPTIONS)
#define XEX_HEADER_PRIVILEGE(priv)			(XEX_HEADER_FLAG(0x0300)+((priv&~0x1f)<<3))
#define XEX_HEADER_EXECUTION_ID				XEX_HEADER_STRUCT(0x400, XEX_EXECUTION_ID)
#define XEX_HEADER_SERVICE_ID_LIST			XEX_HEADER_SIZEDSTRUCT(0x401)
#define XEX_HEADER_WORKSPACE_SIZE			XEX_HEADER_ULONG(0x402)
// #define XEX_HEADER_GAME_RATINGS				XEX_HEADER_FIXED_SIZE(0x403, XEX_NUMBER_GAME_RATING_SYSTEMS)
// #define XEX_HEADER_LAN_KEY					XEX_HEADER_FIXED_SIZE(0x404, XEX_LAN_KEY_SIZE) // XEX_LAN_KEY_SIZE size is 0x10
#define XEX_HEADER_MSLOGO					XEX_HEADER_SIZEDSTRUCT(0x0405)
#define XEX_HEADER_MULTIDISK_MEDIA_IDS		XEX_HEADER_SIZEDSTRUCT(0x0406)
#define XEX_HEADER_ALTERNATE_TITLE_IDS		XEX_HEADER_SIZEDSTRUCT(0x0407)
#define XEX_HEADER_ADDITIONAL_TITLE_MEM		XEX_HEADER_ULONG(0x408)

#endif // _XEXHEADER_H
